doc: update links to doc and parser-worker
cognitedata/reveal pull request #1442
Opened 2021-04-23 09:13 UTC by larsmoa

2021-04-23 09:14 UTC, maksnester approved these changes
👍

2021-04-23 09:14 UTC, maksnester requested changes
actually, the first links have to be changed too (at the beginning)

![image](https://user-images.githubusercontent.com/4989157/115849467-32ebee00-a425-11eb-9164-2f7b3c14f0d5.png)

2021-04-23 09:44 UTC, larsmoa commented
Looks better @maksnester ?

2021-04-25 22:38 UTC, maksnester approved these changes
👍

2021-04-25 22:38 UTC, merged