feat: Cognite3DModel.changeStyledNodeSetAppearance; feat: ByTreeIndexNodeSet - allow empty constructor
cognitedata/reveal pull request #1524
Opened 2021-06-09 17:24 UTC by maksnester

2021-06-09 20:00 UTC, larsmoa requested changes
Looks good - but can you also add a section before Examples in cad-styling.mdx that explains how you add/change/remove styled sets? I'm thinking an example where you e.g. style nodes with treeIndex 0-100.000 in a color, change the color of the styled set and finally remove it (?)

2021-06-10 11:57 UTC, maksnester commented on viewer/src/datamodels/cad/styling/NodeAppearanceProvider.test.ts
> +  test('add/change/remove style triggers called', () => {
sure, good point 👍

2021-06-10 19:02 UTC, larsmoa approved these changes
See suggestions

2021-06-10 19:02 UTC, larsmoa commented on documentation/docs/examples/cad-styling.mdx
> +This is how you can bind a specific appearance to your node set and update it:
```suggestion
`Cognite3DModel.addStyledNodeSet`, `changeStyledNodeSetAppearance` and `removeStyledNodeSet` is used to manage styled set associated with a model:
```

2021-06-11 09:16 UTC, merged