fix: not able to load same model twice [REV-132]
cognitedata/reveal pull request #1555
Opened 2021-06-28 10:42 UTC by larsmoa

Add the ability to load the same model twice, or to add-remove-add the same model.

2021-06-28 11:12 UTC, christjt requested changes
Looks VERY good! Love the refactoring done here. Very clean and waaay more understandable. Only some minor recommendations to make it even more concise.

2021-06-28 11:12 UTC, christjt commented on viewer/src/datamodels/cad/sector/rxSectorUtilities.ts
> -export function handleDetermineSectorsInput(
VERY NICE

2021-06-28 19:52 UTC, larsmoa commented
Thx for good input @christjt - I've done some changes and I also noticed that sectors wasn't made visible on screen until a full batch was loaded. I fixed this and did some minor improvements.

2021-06-29 07:07 UTC, christjt approved these changes

2021-06-29 07:31 UTC, merged