chore: update dependencies
cognitedata/reveal pull request #1577
Opened 2021-08-05 12:05 UTC by larsmoa

Updates a bunch of dependencies within the accepted ranges defined in packages.json

2021-08-05 20:48 UTC, christjt requested changes

2021-08-05 20:48 UTC, christjt commented on documentation/package.json
> +    "react-live": "^2.3.0",
Did Maksim's changes get merged into react-live?

2021-08-06 06:44 UTC, larsmoa commented on documentation/package.json
> +    "react-live": "^2.3.0",
Yes, see https://github.com/FormidableLabs/react-live/releases/tag/v2.3.0

2021-08-06 06:46 UTC, christjt approved these changes

2021-08-06 06:46 UTC, merged