feat: enable locally hosted models in Migration example
cognitedata/reveal pull request #1595
Opened 2021-09-01 19:58 UTC by larsmoa

Add support for locally hosted models to Cognite3DViewer and Cognite3DModel. 

Note that locally hosted models have several limitations due to lack of support from CDF that many Reveal features rely on.

This feature is meant for use in development only, and is not meant to be used in production. The toggle to enable this is not exported in the library and hence hidden to end users.

2021-09-06 14:54 UTC, christjt requested changes

2021-09-06 14:54 UTC, christjt commented on viewer/core/src/public/migration/Cognite3DModel.ts
> +import { NodesApiClient } from '../../../../packages/nodes-api';
wrong import, should be ```@reveal/nodes-api```

2021-09-06 14:54 UTC, christjt commented on viewer/packages/nodes-api/src/NodesCdfClient.ts
> +    return nodes.map(n => {
rename `n` to `node`

2021-09-06 21:46 UTC, larsmoa commented
Comments fixed @christjt. PS! I love the 'Suggestion'-button for small changes.... ;)

2021-09-07 10:09 UTC, christjt commented
> Comments fixed @christjt. PS! I love the 'Suggestion'-button for small changes.... ;)

I see your point, but sometimes I am not exactly sure what the syntax is. And in those cases it is easier to do in an IDE.

2021-09-07 10:09 UTC, christjt approved these changes

2021-09-08 11:07 UTC, merged