feat: set proper update range for partial geometry updates
cognitedata/reveal pull request #1738
Opened 2021-12-02 16:31 UTC by christjt

Before:
![image](https://user-images.githubusercontent.com/6741854/144576195-9396a2f6-157f-46b0-a1ee-f557df838665.png)

After:
![image](https://user-images.githubusercontent.com/6741854/144576217-c4654e06-6f8b-4252-a921-c5cac4f45564.png)

2021-12-03 07:47 UTC, haakonflatval-cognite approved these changes
Looks good, just a small question

2021-12-03 07:47 UTC, haakonflatval-cognite commented on viewer/packages/rendering/src/GeometryBatchingManager.ts
> +    attribute.data.updateRange = { offset, count };
The math looks correct, but I'm just wondering: How does `updateRange` work for `InterleavedBufferAttribute`? Does it update the portion of the attribute you specified, plus everything in-between that resides in the same buffer, which may belong to other attributes?

2021-12-03 08:55 UTC, larsmoa requested changes

2021-12-03 08:55 UTC, larsmoa commented on viewer/packages/rendering/src/GeometryBatchingManager.ts
> +  private setUpdateRange(
I think this should be renamed to `extendUpdateRange`

2021-12-10 17:01 UTC, larsmoa approved these changes

2021-12-10 17:01 UTC, merged