fix: Added Temporary API keys missing in Docs for all map providers
cognitedata/reveal pull request #1767
Opened 2022-01-07 09:51 UTC by pramodcog

Added temporary API keys for all map providers for testing in Docs

2022-01-07 12:49 UTC, christjt approved these changes
LGTM

2022-01-07 12:52 UTC, larsmoa requested changes
Store keys in customScope.ts as we do today to avoid people easily copy-pasting our API keys by accident.

2022-01-10 18:39 UTC, larsmoa approved these changes

2022-01-10 18:39 UTC, larsmoa commented
how should we ensure we catch expiry going forward @pramodcog ?

2022-01-11 08:24 UTC, merged