Better suggested camera config
cognitedata/reveal pull request #1833
Opened 2022-02-04 10:34 UTC by haakonflatval-cognite

This influences how camera is configured on first model load. Inspired by this complaint: https://cognitedata.slack.com/archives/C8A0QGMLN/p1643968454118329

The reasoning is that the camera is now looking at the largest area of the bounding box, whereas earlier it would look at the smaller. Provided screenshots may explain better.

Before: 
![bg1](https://user-images.githubusercontent.com/70905152/152514481-90d2bef4-d080-406d-9033-b459ef272efe.png)

After: 
![bg0](https://user-images.githubusercontent.com/70905152/152514492-354d56ea-2c6d-4d11-b281-7ceab0d916b8.png)

2022-02-04 12:58 UTC, haakonflatval-cognite commented
In the newest update, camera angle is restricted to max. 30 degrees above (below) the horizon.
![Uploading bg2.png…]()

2022-02-07 07:47 UTC, christjt requested changes
Looks good, only a minor NIT

2022-02-07 07:47 UTC, christjt commented on viewer/packages/rendering/src/cameraconfig.ts
> +  }
Concider inverting the if statement to reduce nesting. Also, the `xzProjection` can be covered using the ternary operator.

2022-02-07 08:42 UTC, christjt approved these changes

2022-02-07 08:43 UTC, haakonflatval-cognite commented
Second test is confirmed to fail without the below-30-degree-horizon restriction.

2022-02-07 09:00 UTC, merged

2022-02-07 11:48 UTC, haakonflatval-cognite commented
Turns out this works less-than-well for real-life models. But so did the last one. Oh well, leaving it for now. (It is only in use internally, although it is exposed undocumentedly in `CadNode`.