Add gltf sector cache
cognitedata/reveal pull request #1841
Opened 2022-02-08 09:42 UTC by haakonflatval-cognite

2022-02-09 22:14 UTC, larsmoa commented
Any stats on how well it works?

2022-02-10 07:36 UTC, haakonflatval-cognite commented
> Any stats on how well it works?

It's hard to measure objectively. The current default cache size (300) lets the user turn around at a single spot in the middle of Johan Castberg almost without loading new sectors. Do you have suggestions for better metrics?

2022-02-14 10:20 UTC, larsmoa requested changes
See comment about referencing the default budget.

2022-02-14 10:20 UTC, larsmoa commented on viewer/core/src/datamodels/cad/CadManager.ts
> +    const REPOSITORY_CACHE_SIZE_TO_BUDGET_RATIO = 200 / 15_000_000;
Don't hard-code the default budget - reference `defaultCadModelBudget`

2022-02-14 10:20 UTC, larsmoa commented on viewer/packages/sector-loader/src/GltfSectorLoader.ts
> +      MetricsLogger.trackError(error as Error, { moduleName: 'GltfSectorRepository', methodName: 'loadSector' });
```suggestion
      MetricsLogger.trackError(error as Error, { moduleName: 'GltfSectorLoader', methodName: 'loadSector' });
```

2022-02-14 12:40 UTC, larsmoa approved these changes

2022-02-14 15:07 UTC, merged