improvement: add alternative unit names that doesn't end with S
cognitedata/reveal pull request #1842
Opened 2022-02-08 13:11 UTC by larsmoa

Add alternative spelling of units to be more resilient.

2022-02-08 15:06 UTC, larsmoa commented
> Looks good, but should we also ensure resilience towards e.g. lower-case spellings of the units?

Probably a good idea, yes...

2022-02-09 07:27 UTC, haakonflatval-cognite approved these changes
Should remove the console log, otherwise looks good! :+1:

2022-02-09 07:27 UTC, haakonflatval-cognite commented on viewer/core/src/datamodels/cad/CadModelFactory.ts
> +    console.log(metadata);
```suggestion
```

2022-02-09 07:59 UTC, haakonflatval-cognite requested changes
Also, this was caught in the visual tests: "Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined".

Seems like a null check is needed (although I don't really see how this passes the type check, which doesn't allow undefined's in the `getDistanceToMeterConversionFactor` function

2022-02-10 07:33 UTC, haakonflatval-cognite approved these changes

2022-02-10 08:28 UTC, merged