refactor: move cadnode
cognitedata/reveal pull request #1947
Opened 2022-03-03 08:16 UTC by haakonflatval-cognite

2022-03-09 10:33 UTC, christjt requested changes

2022-03-09 10:33 UTC, christjt commented on viewer/packages/rendering/src/rendering/EffectRenderManager.ts
> +    },
This probably deserves a type

2022-03-09 10:33 UTC, christjt commented on viewer/packages/rendering/src/sector/SceneComponentsProvider.ts
> +  getGhostScene(): THREE.Scene;
Any way to reduce this into only two functions? With only `splitScene()` and `restoreScene()`?

2022-04-29 16:05 UTC, larsmoa commented
Dead, @haakonflatval-cognite ?

2022-05-25 10:58 UTC, christjt commented
@larsmoa @haakonflatval-cognite Some of the changes here do not make sense anymore after the rendering pipeline changes. I will reimplement what has been done here. So we can leave it up until that is done (might take a lot of inspiration from this PR).

2022-05-30 14:34 UTC, christjt commented
Closing this in favor of: https://github.com/cognitedata/reveal/pull/2173

2022-05-30 14:34 UTC, closed without merging