fix: Removed metrics for CameraManager and CustomDataSource
cognitedata/reveal pull request #2131
Opened 2022-05-12 15:58 UTC by Savokr

Removed logging metrics for `CameraManager` and `CustomDataSource` because when they were defined on options passed to `Cognite3DViewer` it was trying to send the whole instance of the class which obviously failed and was causing stack overflow error.

2022-05-12 18:30 UTC, larsmoa requested changes
I think we should switch to `pick` from lodash (https://lodash.com/docs/4.17.15#pick).

Also, I think we should address the fact that a error in metrics can cause infinite loops

2022-05-12 20:28 UTC, christjt commented
@larsmoa can we maybe just add this as a hotfix such that we can release a patch, and then address these issues properly after?

2022-05-13 10:37 UTC, christjt approved these changes
LGTM

2022-05-13 10:43 UTC, larsmoa approved these changes

2022-05-13 10:48 UTC, merged