feat: enable point blending and EDL together
cognitedata/reveal pull request #2682
Opened 2022-11-10 15:36 UTC by haakonflatval-cognite

#### Type of change

![Feat](https://img.shields.io/badge/Type-Feat-green)  

#### Jira ticket :blue_book:

https://cognitedata.atlassian.net/browse/REV-547

## Description :pencil:

This allows for using EDL and point cloud blending together.

## How has this been tested? :mag:

By... Enabling EDL and point blending simultaneously

## Test instructions :information_source:

Open examples with your favorite point cloud, enable point blending.

## Checklist :ballot_box_with_check:

- [x] I am proud of this feature.
- [x] I have performed a self-review of my own code.
- [x] I have added PR type (Feat, Bug, Chore, Test, Docs, Style, Refactor) to the PR title.
- [ ] I have manually tested this for different scenarios (different models, formats, devices, browsers).
- [ ] I have commented my code in hard-to-understand areas.
- [x] I have made corresponding changes to the public documentation.
- [ ] I have added unit and visuals tests to prove that my feature works to the best of my ability.
- [x] I have refactored the code for readability to the best of my ability.
- [ ] I have checked that my changes do not introduce regressions in the public documentation.
- [x] I have outlined any known defects / lacking capabilities in the contents of this PR.
- [x] I have listed any remaining work that should follow this PR in the description or jira/miro/etc.
- [x] I have added TSDoc to any public facing changes.
- [x] I have added "developer documentation" in any package README.md that is related / applicable to this PR.
- [x] I have noted down and am currently tracking any technical debt introduced in this PR.
- [x] I have thoroughly thought about the architecture of this implementation.
- [ ] I have asked peers to test this feature.

2022-11-10 16:23 UTC, christjt requested changes
Great that you were able to fix this!

2022-11-11 09:37 UTC, haakonflatval-cognite commented on viewer/packages/rendering/src/glsl/pointcloud/edl.glsl
> +// Passed logDepthTexture is assumed to have logarithmic depth value written to alpha channel.
No, it's a color buffer where we record logarithmic depth (in `pointcloud.frag`, when EDL is active).

2022-11-11 09:38 UTC, haakonflatval-cognite commented on viewer/packages/rendering/src/render-pipeline-providers/PointCloudRenderPipelineProvider.ts
> +    logDepthAndDepthOutput: THREE.WebGLRenderTarget;
Yep.. The color output is logarithmic depth, and the depth output is just normal linear depth

2022-11-11 12:01 UTC, christjt approved these changes

2022-11-11 12:04 UTC, merged