Added SettableRenderTarget interface with setOutputRenderTarget function
cognitedata/reveal pull request #2850
Opened 2023-01-05 14:45 UTC by astrid-kg

#### Type of change

![Feat](https://img.shields.io/badge/Type-Feat-green)  
![Bug](https://img.shields.io/badge/Type-Bug-red) 
![Test](https://img.shields.io/badge/Type-Test-blueviolet) 
![Docs](https://img.shields.io/badge/Type-Docs-blue) 
![Style](https://img.shields.io/badge/Type-Style-blue) 
![Refactor](https://img.shields.io/badge/Type-Refactor-lightgrey) 
![Chore](https://img.shields.io/badge/Type-Chore-lightgrey) 

#### Jira ticket :blue_book:

https://cognitedata.atlassian.net/browse/

## Description :pencil:

## How has this been tested? :mag:

## Test instructions :information_source:

## Checklist :ballot_box_with_check:

- [ ] I am proud of this feature.
- [ ] I have performed a self-review of my own code.
- [ ] I have added PR type (Feat, Bug, Chore, Test, Docs, Style, Refactor) to the PR title.
- [ ] I have manually tested this for different scenarios (different models, formats, devices, browsers).
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the public documentation.
- [ ] I have added unit and visuals tests to prove that my feature works to the best of my ability.
- [ ] I have refactored the code for readability to the best of my ability.
- [ ] I have checked that my changes do not introduce regressions in the public documentation.
- [ ] I have outlined any known defects / lacking capabilities in the contents of this PR.
- [ ] I have listed any remaining work that should follow this PR in the description or jira/miro/etc.
- [ ] I have added TSDoc to any public facing changes.
- [ ] I have added "developer documentation" in any package README.md that is related / applicable to this PR.
- [ ] I have noted down and am currently tracking any technical debt introduced in this PR.
- [ ] I have thoroughly thought about the architecture of this implementation.
- [ ] I have asked peers to test this feature.

2023-01-06 14:07 UTC, Savokr approved these changes
Looks good, a few comments but works fine as is. Tested in safari and chrome MacBook M1, works fine in chrome but not working in safari (both standard render target and custom) with webgl metal backend (which is default settings). Measurement labels are rendered but model and reveal window itself are not, just white background.

2023-01-06 14:33 UTC, Savokr requested changes
Found one bug, when `includeUI` flag is set to false in examples UI, Reveal resolution is reduced and not set to initial value before taking screenshot. Video available here: https://cognitedata.atlassian.net/browse/REV-643?focusedCommentId=232934

2023-01-10 20:56 UTC, larsmoa commented on viewer/packages/api/src/public/migration/Cognite3DViewer.ts
>        // Disregard pixelRatio to get the screenshot in requested resolution.
Although that would be good, I think its might be hard to do @Savokr - a new canvas means a new WebGL context which means that everything must be re-initialized.

2023-01-10 20:58 UTC, larsmoa commented on viewer/packages/api/src/public/migration/Cognite3DViewer.ts
> +        this.revealManager.setOutputRenderTarget(null);
This is not something we need to support.

2023-01-12 07:28 UTC, astrid-kg commented on viewer/packages/api/src/public/migration/Cognite3DViewer.ts
> +        // To esure that the render is done to the screenshot canvas, we clear the custom
Done!

2023-01-18 09:11 UTC, Savokr approved these changes
Looks good, tested in safari and chrome, works just fine!

2023-01-18 09:19 UTC, merged