feat(react-components): clicked node hook
cognitedata/reveal pull request #3557
Opened 2023-08-07 14:28 UTC by haakonflatval-cognite

#### Type of change

![Feat](https://img.shields.io/badge/Type-Feat-green)  

#### Jira ticket :blue_book:

https://cognitedata.atlassian.net/browse/UX-1147

## Description :pencil:

Adds a `useClickedNode` hook which uses `react-query` under the hood to listen to and fetch data related to Cad Node clicking.

Known issues:
- On clicking the second node after one is already clicked, the hook will spurt out three updates:
  - The first result once again
  - `undefined`
  - The result belonging to the second node

This may just be alright, but feels unnecessary

## How has this been tested? :mag:

In the story.

## Test instructions :information_source:

## Checklist :ballot_box_with_check:

- [x] I am proud of this feature.
- [x] I have performed a self-review of my own code.
- [x] I have added PR type (Feat, Bug, Chore, Test, Docs, Style, Refactor) to the PR title.
- [ ] I have manually tested this for different scenarios (different models, formats, devices, browsers).
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the public documentation.
- [ ] I have added unit and visuals tests to prove that my feature works to the best of my ability.
- [ ] I have refactored the code for readability to the best of my ability.
- [ ] I have checked that my changes do not introduce regressions in the public documentation.
- [ ] I have outlined any known defects / lacking capabilities in the contents of this PR.
- [ ] I have listed any remaining work that should follow this PR in the description or jira/miro/etc.
- [ ] I have added TSDoc to any public facing changes.
- [ ] I have added "developer documentation" in any package README.md that is related / applicable to this PR.
- [ ] I have noted down and am currently tracking any technical debt introduced in this PR.
- [ ] I have thoroughly thought about the architecture of this implementation.
- [ ] I have asked peers to test this feature.

2023-08-10 14:19 UTC, Savokr requested changes
Looks really good but a few things to consider.

2023-08-10 14:19 UTC, Savokr commented on react-components/stories/ClickedNode.stories.tsx
Do we need a separate story for that hook? Maybe it's fine to put it inside `HighlightNode` story in addition to what is used there and just explain the difference in comments.

2023-08-14 10:39 UTC, Savokr commented on react-components/src/hooks/useClickedNode.tsx
> +  }
Yeah, we can do it later. Exposing just the intersection now should also be fine I think

2023-08-14 11:08 UTC, haakonflatval-cognite commented on react-components/stories/ClickedNode.stories.tsx
Yes, okay - we will probably have too many stories eventually :sweat_smile:

2023-08-14 11:09 UTC, haakonflatval-cognite commented on react-components/stories/ClickedNode.stories.tsx
I don't think it's necessary to include the old method of providing node data.. To be honest, this should replace it.

2023-08-14 12:36 UTC, Savokr approved these changes
Looks good!

2023-08-16 08:14 UTC, Savokr approved these changes
LGTM

2023-08-16 08:18 UTC, merged