fix(react-components): Toolbar styling and missing buttons toggle
cognitedata/reveal pull request #3653
Opened 2023-08-30 15:01 UTC by pramodcog

#### Type of change

![Bug](https://img.shields.io/badge/Type-Bug-red) 

#### Jira ticket :blue_book:

https://cognitedata.atlassian.net/browse/

## Description :pencil:
The toolbar is corrected to match Figma styling
Add toggle action for all buttons 

## How has this been tested? :mag:

In storybook

## Test instructions :information_source:

`cd react-components && yarn && yarn build && yarn storybook`
Select `Toolbar` example

## Checklist :ballot_box_with_check:

- [x] I am proud of this feature.
- [x] I have performed a self-review of my own code.
- [x] I have added PR type (Feat, Bug, Chore, Test, Docs, Style, Refactor) to the PR title.
- [x] I have manually tested this for different scenarios (different models, formats, devices, browsers).
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the public documentation.
- [ ] I have added unit and visuals tests to prove that my feature works to the best of my ability.
- [ ] I have refactored the code for readability to the best of my ability.
- [ ] I have checked that my changes do not introduce regressions in the public documentation.
- [ ] I have outlined any known defects / lacking capabilities in the contents of this PR.
- [ ] I have listed any remaining work that should follow this PR in the description or jira/miro/etc.
- [ ] I have added TSDoc to any public facing changes.
- [ ] I have added "developer documentation" in any package README.md that is related / applicable to this PR.
- [ ] I have noted down and am currently tracking any technical debt introduced in this PR.
- [ ] I have thoroughly thought about the architecture of this implementation.
- [ ] I have asked peers to test this feature.

2023-09-05 14:01 UTC, pramodcog commented
> ![image](https://user-images.githubusercontent.com/6595726/265637653-d2fae496-bc37-462c-8bef-334a78f7ca95.png)
> 
> Is incorrect vs. Figma styling
> 
> ![image](https://user-images.githubusercontent.com/6595726/265637755-cb942efc-4c1f-42ca-b2d7-94de98bb47c6.png)

Confirmed with Kerem on the styling, he is good with the current styling as it is the default css property set in the `Menu.Item`

2023-09-08 13:32 UTC, christjt requested changes
Looks good, a few comments.

2023-09-08 13:32 UTC, christjt commented on react-components/src/components/RevealToolbar/LayersButton.tsx
> +  const outsideClick = (ref: RefObject<HTMLElement | null>): void => {
This is a hook. The convention use to prefix the name with `use`

2023-09-08 13:32 UTC, christjt commented on react-components/src/components/RevealToolbar/LayersButton.tsx
> +        if (ref.current !== null && !ref.current.contains(event.target as Node)) {
What happens if event.target isn't a Node here?

2023-09-08 13:32 UTC, christjt commented on react-components/src/components/RevealToolbar/RevealToolbar.tsx
> +      <StyledToolBar {...restProps}>
Seem to be getting a type error here.

2023-09-08 13:37 UTC, christjt requested changes
React spews out an error on initial click on of the layers button.
![image](https://github.com/cognitedata/reveal/assets/6595726/d32ab51c-5294-4762-8d58-626fcdc107f1)

2023-09-11 13:12 UTC, pramodcog commented
> React spews out an error on initial click on of the layers button. ![image](https://user-images.githubusercontent.com/6595726/266627373-d32ab51c-5294-4762-8d58-626fcdc107f1.png)

This is coming from `cogs.js`, I don't have a workaround currently

2023-09-13 11:25 UTC, christjt approved these changes
👍

2023-09-13 13:15 UTC, merged