fix(react-components): missing styling type for 360 annotation
cognitedata/reveal pull request #4261
Opened 2024-02-26 21:04 UTC by pramodcog

#### Type of change

![Bug](https://img.shields.io/badge/Type-Bug-red) 

#### Jira ticket :blue_book:

https://cognitedata.atlassian.net/browse/

## Description :pencil:
 Exported missing type for 360 annotation styling

## How has this been tested? :mag:

## Test instructions :information_source:

## Checklist :ballot_box_with_check:

- [ ] I am proud of this feature.
- [ ] I have performed a self-review of my own code.
- [ ] I have added PR type (Feat, Bug, Chore, Test, Docs, Style, Refactor) to the PR title.
- [ ] I have manually tested this for different scenarios (different models, formats, devices, browsers).
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the public documentation.
- [ ] I have added unit and visuals tests to prove that my feature works to the best of my ability.
- [ ] I have refactored the code for readability to the best of my ability.
- [ ] I have checked that my changes do not introduce regressions in the public documentation.
- [ ] I have outlined any known defects / lacking capabilities in the contents of this PR.
- [ ] I have listed any remaining work that should follow this PR in the description or jira/miro/etc.
- [ ] I have added TSDoc to any public facing changes.
- [ ] I have added "developer documentation" in any package README.md that is related / applicable to this PR.
- [ ] I have noted down and am currently tracking any technical debt introduced in this PR.
- [ ] I have thoroughly thought about the architecture of this implementation.
- [ ] I have asked peers to test this feature.

2024-02-28 10:00 UTC, haakonflatval-cognite requested changes
A couple of comments

2024-02-28 10:00 UTC, haakonflatval-cognite commented on react-components/src/components/NodeCacheProvider/Image360AnnotationCache.ts
> +          });
This is not safe - we should not just assume that this async call will be done executing before the rest of this function is run

2024-02-28 10:00 UTC, haakonflatval-cognite commented on react-components/src/components/NodeCacheProvider/types.ts
>  };
I wonder if we should just return the `Image360AnnotationObject` instead of the annotation info and the centers

2024-02-28 10:02 UTC, haakonflatval-cognite commented on react-components/src/components/NodeCacheProvider/types.ts
>  };
Actually - we will need the `AssetAnnotationImage360Info` :thinking: Perhaps this is okay - but it feels like we might as well give the user the option to use `Image360Annotation` too

2024-02-29 08:27 UTC, haakonflatval-cognite commented on react-components/src/components/NodeCacheProvider/Image360AnnotationCache.ts
> +          console.log('assetId, center', assetId, center);
:raised_eyebrow:

2024-02-29 08:27 UTC, haakonflatval-cognite commented on react-components/src/components/NodeCacheProvider/Image360AnnotationCache.ts
> +            centerPosition.add(center);
Do you mean to use `add` here? Don't we only want to return the `centerPosition` of the `revisionAnnotation` that has the same ID as `annotationInfo.annotation`?

2024-02-29 09:24 UTC, pramodcog commented on react-components/src/components/NodeCacheProvider/Image360AnnotationCache.ts
> +          console.log('assetId, center', assetId, center);
🙅

2024-02-29 09:58 UTC, haakonflatval-cognite approved these changes

2024-02-29 09:58 UTC, merged