feat(react-components): support node coloring in Reveal3D resources, rename types and bump version 0.53.0
cognitedata/reveal pull request #4665
Opened 2024-07-15 13:20 UTC by haakonflatval-cognite

#### Type of change

![Feat](https://img.shields.io/badge/Type-Feat-green)  

#### Jira ticket :blue_book:

https://cognitedata.atlassian.net/browse/BND3D-4479

## Description :pencil:

Allow programmers to color CAD-models by node IDs / tree indices

## How has this been tested? :mag:

TBA

## Test instructions :information_source:

## Checklist :ballot_box_with_check:

- [x] I am proud of this feature.
- [ ] I have performed a self-review of my own code.
- [x] I have added PR type (Feat, Bug, Chore, Test, Docs, Style, Refactor) to the PR title.
- [ ] I have manually tested this for different scenarios (different models, formats, devices, browsers).
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the public documentation.
- [ ] I have added unit and visuals tests to prove that my feature works to the best of my ability.
- [ ] I have refactored the code for readability to the best of my ability.
- [ ] I have checked that my changes do not introduce regressions in the public documentation.
- [ ] I have outlined any known defects / lacking capabilities in the contents of this PR.
- [ ] I have listed any remaining work that should follow this PR in the description or jira/miro/etc.
- [ ] I have added TSDoc to any public facing changes.
- [ ] I have added "developer documentation" in any package README.md that is related / applicable to this PR.
- [ ] I have noted down and am currently tracking any technical debt introduced in this PR.
- [ ] I have thoroughly thought about the architecture of this implementation.
- [ ] I have asked peers to test this feature.

2024-07-15 14:20 UTC, j-bjorne requested changes

2024-07-15 14:20 UTC, j-bjorne commented on react-components/stories/Reveal3DResources.stories.tsx
> +            { nodeIds: [7152264879809192, 7899489067916664], style: { visible: false } }
Should we allow both node ids and treeindex sets in node groups, or should we encourage the user to transform from nodeids to treeindex sets for usage with low end apis

2024-07-16 09:36 UTC, j-bjorne approved these changes
Lgtm, still see some node styling groups in the definitions and such, but I am guessing they are used elsewhere

2024-07-16 10:15 UTC, haakonflatval-cognite commented
> Lgtm, still see some node styling groups in the definitions and such, but I am guessing they are used elsewhere

Yes, they are still used internally where we create styling from asset mappings / FDM instances.

Btw, I'll bump the react-components version before merging

2024-07-16 10:19 UTC, merged