fix: return simple pojo and not Vector3
cognitedata/reveal pull request #4674
Opened 2024-07-23 14:19 UTC by nabati

#### Type of change
![Bug](https://img.shields.io/badge/Type-Bug-red) 

#### Jira ticket :blue_book:

Thread: https://cognitedata.slack.com/archives/C8A0QGMLN/p1721723669208189

## Description :pencil:

TLDR: `getCurrentState` was returning sets of Vector3 with the required fields rather than simple POJOs. IMHO this is slightly bad form even though Typescript allows it, so this PR remaps the Vector3s to POJOs. 

## How has this been tested? :mag:

Didn't

## Test instructions :information_source:

## Checklist :ballot_box_with_check:

2024-07-23 14:20 UTC, haakonflatval-cognite approved these changes
LGTM :+1:

2024-07-23 14:23 UTC, haakonflatval-cognite requested changes

2024-07-23 14:23 UTC, haakonflatval-cognite commented on viewer/packages/api/src/utilities/ViewStateHelper.ts
> +          z: cameraPosition.z
:face_with_peeking_eye:

2024-07-23 14:31 UTC, nabati commented on viewer/packages/api/src/utilities/ViewStateHelper.ts
> +          z: cameraPosition.z
😱

2024-07-24 08:30 UTC, haakonflatval-cognite approved these changes

2024-07-24 08:30 UTC, merged