fix(react-components): cogs fixups and bump to 0.60.2
cognitedata/reveal pull request #4803
Opened 2024-10-10 15:45 UTC by haakonflatval-cognite

#### Type of change

![Chore](https://img.shields.io/badge/Type-Chore-lightgrey) 

#### Jira ticket :blue_book:

https://cognitedata.atlassian.net/browse/

## Description :pencil:

Various format fixes related to the cogs-v10 migration

## How has this been tested? :mag:

## Test instructions :information_source:

## Checklist :ballot_box_with_check:

- [x] I am proud of this feature.
- [ ] I have performed a self-review of my own code.
- [x] I have added PR type (Feat, Bug, Chore, Test, Docs, Style, Refactor) to the PR title.
- [ ] I have manually tested this for different scenarios (different models, formats, devices, browsers).
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the public documentation.
- [ ] I have added unit and visuals tests to prove that my feature works to the best of my ability.
- [ ] I have refactored the code for readability to the best of my ability.
- [ ] I have checked that my changes do not introduce regressions in the public documentation.
- [ ] I have outlined any known defects / lacking capabilities in the contents of this PR.
- [ ] I have listed any remaining work that should follow this PR in the description or jira/miro/etc.
- [ ] I have added TSDoc to any public facing changes.
- [ ] I have added "developer documentation" in any package README.md that is related / applicable to this PR.
- [ ] I have noted down and am currently tracking any technical debt introduced in this PR.
- [ ] I have thoroughly thought about the architecture of this implementation.
- [ ] I have asked peers to test this feature.

2024-10-11 10:20 UTC, nilscognite reviewed
Fix the SettingsItem and make the option button as they where before

2024-10-11 10:20 UTC, nilscognite commented on react-components/src/architecture/base/commands/SettingsItem.ts
> +export class CommandSettingsItem implements SettingsItem {
I think this is not necessary and overcomplicated. All commands has their own unique id as a getter. You simple make a DividerCommand from BaseCommand, and override a minimum. Should be about nothing. Then you have everything you need, including the unique number

2024-10-14 11:11 UTC, nilscognite requested changes
I simply don't understand that the new redesign option in the Settings panel is better than it was.

2024-10-14 14:32 UTC, haakonflatval-cognite commented on react-components/src/architecture/base/concreteCommands/SettingsCommand.ts
> +    this.add(new PointCloudDividerCommand());
![bg0](https://github.com/user-attachments/assets/6ad33089-8af5-4ba2-88b8-2f4cae894ff0)
It looks like this now, after I removed the second divider. I was worried it wouldn't be clear that the slider was associated to the label above, and not below. But I think it's reasonably clear, looking at it now. I'll keep it like this

2024-10-14 22:24 UTC, nilscognite commented on react-components/src/architecture/base/concreteCommands/SettingsCommand.ts
> +    this.add(new PointCloudDividerCommand());
The post is 

**Point settings:**
Size:      
Color:
Shape:
Filter:

2024-10-17 11:34 UTC, nilscognite approved these changes
LGTM

2024-10-17 11:38 UTC, merged