feat (react-components): Tree view
cognitedata/reveal pull request #4804
Opened 2024-10-11 09:41 UTC by nilscognite

#### Type of change

![Feat](https://img.shields.io/badge/Type-Feat-green)  

#### Jira ticket :blue_book:

https://cognitedata.atlassian.net/browse/

## Description :pencil:
![image](https://github.com/user-attachments/assets/abc2376f-9b3d-47f0-9957-bf114ee31334)
## How has this been tested? :mag:

## Test instructions :information_source:

## Checklist :ballot_box_with_check:

- [ ] I am proud of this feature.
- [ ] I have performed a self-review of my own code.
- [ ] I have added PR type (Feat, Bug, Chore, Test, Docs, Style, Refactor) to the PR title.
- [ ] I have manually tested this for different scenarios (different models, formats, devices, browsers).
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the public documentation.
- [ ] I have added unit and visuals tests to prove that my feature works to the best of my ability.
- [ ] I have refactored the code for readability to the best of my ability.
- [ ] I have checked that my changes do not introduce regressions in the public documentation.
- [ ] I have outlined any known defects / lacking capabilities in the contents of this PR.
- [ ] I have listed any remaining work that should follow this PR in the description or jira/miro/etc.
- [ ] I have added TSDoc to any public facing changes.
- [ ] I have added "developer documentation" in any package README.md that is related / applicable to this PR.
- [ ] I have noted down and am currently tracking any technical debt introduced in this PR.
- [ ] I have thoroughly thought about the architecture of this implementation.
- [ ] I have asked peers to test this feature.

2024-10-24 20:24 UTC, danpriori requested changes
It looks good to me overall. Nice work!

I really liked the structure of the classes and how it organized the logic to load the nodes, children and siblings. It is relatively easy to understand and I believe it is easy to scale.

I have some comments that I find interesting to address, such as the callbacks that the application can use to receive the list of selected TreeNodes, and also the change of some files and functions to facilitate future changes and improvements in the organization and structure of some components and other comments for reflection and questions that I have about it.

We can discuss some points for changes in the future, because I don't think that these things that I raised are blockers now. Perhaps the crucial point at the moment is my questions about the callbacks that the application would use to receive the Array of TreeNodes.

I tested a little and the performance seems to be good. I forced the tree generator to create more sub levels and apparently the performance remains reasonable.

I'm gonna test a little more trying to do some stress test as well. But looks like stable so far.

2024-10-28 07:32 UTC, nilscognite commented on react-components/src/components/Architecture/TreeView/TreeView.tsx
> +/* eslint-disable react/prop-types */
Fixed

2024-10-28 07:32 UTC, nilscognite commented on react-components/src/components/Architecture/TreeView/TreeView.tsx
> +      // ref={htmlRef}
Fixed

2024-10-28 07:32 UTC, nilscognite commented on react-components/src/components/Architecture/TreeView/TreeViewNode.tsx
> +/* eslint-disable react/prop-types */
We need this for some reason

2024-10-28 07:38 UTC, nilscognite commented on react-components/src/components/Architecture/TreeView/TreeViewNode.tsx
> +          marginLeft: level * gapToChildren + 'px'
Ok

2024-10-28 07:39 UTC, nilscognite commented on react-components/stories/TreeView.stories.tsx
> +function createTreeMock(lazyLoading: boolean): ITreeNode {
Done

2024-10-28 07:39 UTC, nilscognite commented on react-components/src/components/Architecture/TreeView/TreeViewNode.tsx
> +  const [, forceUpdate] = useReducer((x) => x + 1, 0);
It work pretty well and saved me from making tons of code lines.

2024-10-28 07:41 UTC, nilscognite commented on react-components/src/components/Architecture/TreeView/TreeViewNode.tsx
> +        marginLeft: (level + 1) * gapToChildren + 'px'
Fixed

2024-10-28 07:47 UTC, nilscognite reviewed
I have fixed some of the easy things. The rest I have to discuss with you

2024-10-28 07:58 UTC, nilscognite commented on react-components/src/components/Architecture/TreeView/TreeView.tsx
> +        <TreeViewNode node={node} key={index} level={0} props={props} />
I added a getSelectedNodes and getCheckedNodes method on TreeNode.

2024-10-31 07:52 UTC, nilscognite commented on react-components/src/components/Architecture/TreeView/TreeViewNode.tsx
> +}
done

2024-10-31 14:40 UTC, danpriori approved these changes
Based on our discussion and with the review of the new changes, LGTM. Dont forget to remove the unnecessary commits from the another PR.

Nice work!

2024-10-31 18:35 UTC, merged